# Note the extra ':' prefixes so vars can be accessed like keys
# e.g. JSHUB_JAVASCRIPT_TESTER[:test_run][:vendor][:site]
# ref: http://blog.innovativethought.net/2009/01/02/making-configuration-files-with-yaml-revised/
development: &non_production_settings
  :test_run:
    :vendor:
      :name: secret
      :user: secret
      :password: secret
      # URL to Litmus API, e.g. http://<username>.litmusapp.com/
      :site: secret
      # Test Run URL pattern for public server, e.g. http://some.server.com:81/core/test/external/%s/unit/%s
      :url_pattern: secret
  :continuous_integration:
    :port: 3000
    :reports_path: test/reports
    # URL prefix to test server, e.g. http://some.server.com/core/
    :base_url: http://localhost:3000/
      
test:
  <<: *non_production_settings

production:
  <<: *non_production_settings

passenger:
  <<: *non_production_settings
  
gromit:
  <<: *non_production_settings
  
jshub:
  <<: *non_production_settings
